{{- $name := include "archinfra.tls" . -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name -}}
{{- if $existing }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  ca.crt: {{ index $existing.data "ca.crt" | quote }}
  tls.crt: {{ index $existing.data "tls.crt" | quote }}
  tls.key: {{ index $existing.data "tls.key" | quote }}
{{- else }}
{{- $cn := include "archinfra.eshost" . -}}
{{- $ca := genCA (printf "%s-ca" $cn) 3650 -}}
{{- $sans := list $cn (printf "%s-es" .Release.Name) (printf "%s-es.%s.svc" .Release.Name .Release.Namespace) (printf "*.%s-es-headless.%s.svc.cluster.local" .Release.Name .Release.Namespace) "localhost" -}}
{{- $cert := genSignedCert $cn nil $sans 3650 $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  ca.crt: {{ $ca.Cert | b64enc | quote }}
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
{{- end }}
