apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "archinfra.esname" . }}-config
data:
  elasticsearch.yml: |
    cluster.name: {{ .Release.Name | quote }}
    node.name: ${HOSTNAME}
    network.host: 0.0.0.0
    node.store.allow_mmap: false
    xpack.security.enabled: true
    xpack.security.autoconfiguration.enabled: false
    xpack.security.http.ssl.enabled: true
    xpack.security.http.ssl.key: certs/tls.key
    xpack.security.http.ssl.certificate: certs/tls.crt
    xpack.security.http.ssl.certificate_authorities: [ "certs/ca.crt" ]
    xpack.security.transport.ssl.enabled: true
    xpack.security.transport.ssl.key: certs/tls.key
    xpack.security.transport.ssl.certificate: certs/tls.crt
    xpack.security.transport.ssl.certificate_authorities: [ "certs/ca.crt" ]
    xpack.security.transport.ssl.verification_mode: certificate
    {{- if eq (int .Values.elasticsearch.replicas) 1 }}
    discovery.type: single-node
    {{- else }}
    discovery.seed_hosts: [ "{{ include "archinfra.headless" . }}.{{ .Release.Namespace }}.svc.cluster.local" ]
    {{- if .Values.elasticsearch.bootstrapCluster }}
    cluster.initial_master_nodes:
    {{- range $i := until (int .Values.elasticsearch.replicas) }}
      - "{{ $.Release.Name }}-es-{{ $i }}"
    {{- end }}
    {{- end }}
    {{- end }}
