apiVersion: v1
kind: Service
metadata:
  name: {{ include "archinfra.eshttp" . }}
  labels:
    app.kubernetes.io/name: archinfra-elasticsearch
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: archinfra-elasticsearch
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: https
      port: 9200
      targetPort: https
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "archinfra.headless" . }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: archinfra-elasticsearch
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: transport
      port: 9300
      targetPort: transport
