arch: amd64
image:
  registry: sealos.hub:5000/kube4
  elasticsearch: elasticsearch
  kibana: kibana
  fluentBit: fluent-bit
  curl: curl
  exporter: elasticsearch-exporter
  tagElasticsearch: 9.5.5-amd64
  tagKibana: 9.5.5-amd64
  tagFluentBit: 5.1.3-amd64
  tagCurl: 8.16.0-amd64
  tagExporter: 1.11.0-amd64
  pullPolicy: IfNotPresent
auth:
  existingSecret: elasticsearch-auth
bootstrap:
  enabled: false
elasticsearch:
  replicas: 1
  bootstrapCluster: true
  storageClass: ""
  storageSize: 30Gi
  heap: 2g
  resources:
    requests: {cpu: 500m, memory: 2Gi}
    limits: {cpu: "1", memory: 4Gi}
kibana:
  enabled: true
  resources:
    requests: {cpu: 250m, memory: 1Gi}
    limits: {cpu: "1", memory: 2Gi}
fluentBit:
  enabled: true
  bufferSize: 5G
  resources:
    requests: {cpu: 50m, memory: 128Mi}
    limits: {cpu: 500m, memory: 512Mi}
lifecycle:
  retentionDays: 14
observability:
  enabled: true
  serviceMonitor: true
  prometheusRule: true
